# Generated by Django 3.1.2 on 2020-12-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderprocess',
            name='being_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderprocess',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
