# Generated by Django 3.1.3 on 2020-12-10 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201210_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='OrderProcesses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.orderprocess'),
        ),
    ]
